name: Manual workflow dispatch

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Envoriment to deploy to"
                type: environment
                required: true
                default: 'Development'
            logLevel:
                description: 'Log level to use'
                required: true
                default: 'info'
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: "Tags to deploy"
                required: false
                type: boolean
jobs:
    manual-job:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: Display inputs
              run: |
                echo "Env: ${{ github.event.inputs.environment }}"
                echo "Log Level: ${{ github.event.inputs.logLevel }}"
                echo "Deploy Tags: ${{ github.event.inputs.tags }}"